import {V,clamp,boundsOf} from './math.js';
import {pickMesh,importSTL,importOBJ,exportSTL,exportOBJ,rectangle,circle} from './kernel.js';
import {newDocument,demoDocument,uid,History,ModelEvaluator,MATERIALS,parameters,validateDocument,expression} from './document.js';
import {Renderer} from './renderer.js';
import {icon,hydrateIcons} from './icons.js';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n,d=2)=>Number(n).toLocaleString('en-US',{maximumFractionDigits:d});
const clone=v=>structuredClone(v);
const state={doc:demoDocument(),model:{bodies:[],sketches:[],errors:[],timeline:[]},selected:null,selectedFeature:null,tab:'solid',history:new History(),form:null,sketch:null,measure:null,nav:'select',dirty:false,ready:false,preview:false,folders:{bodies:true,sketches:false,origin:false,settings:false},showSketches:false};
let renderer,worker,workerBusy=false,revision=0,pending=null,saveTimer,rebuildTimer,firstModel=true,db=null,watchdog,hoverTimer,saveVersion=0,saveLabel='Local workspace';
const commands=[
 ['create-sketch','Create sketch','sketch','S'],['box','Box','cube','B'],['cylinder','Cylinder','cylinder',''],['sphere','Sphere','sphere',''],['torus','Torus','torus',''],['extrude','Extrude sketch','extrude','E'],['revolve','Revolve sketch','revolve',''],['hole','Hole','hole','H'],['boolean','Combine bodies','boolean',''],['move','Move / rotate / scale','move','M'],['pattern','Pattern bodies','pattern',''],['appearance','Appearance','appearance','A'],['measure','Measure','measure','I'],['section','Section analysis','section',''],['parameters','User parameters','parameters',''],['import','Import mesh or project','import',''],['save','Save Alloy project','save','⌘ S'],['export-stl','Export STL','export',''],['export-obj','Export OBJ','export',''],['drawing','Export projected SVG drawing','drawing',''],['screenshot','Capture PNG','camera',''],['fit','Fit to view','fit','F'],['home','Home view','home',''],['projection','Toggle perspective','cube','P'],['grid','Toggle grid','grid','G'],['explode','Exploded view','explode',''],['undo','Undo','undo','⌘ Z'],['redo','Redo','redo','⇧ ⌘ Z'],['delete','Delete selected body','trash','⌫'],['new','New design','file',''],['projects','Design library','library',''],['help','Keyboard shortcuts','help','?'],['diagnostics','Engine diagnostics','info','']
];
const commandMeta=id=>commands.find(x=>x[0]===id)||[id,id,id,''];
const featureIcon=type=>({box:'cube',sketch:'sketch',extrude:'extrude',hole:'hole',cylinder:'cylinder',sphere:'sphere',torus:'torus',pattern:'pattern',move:'move',boolean:'boolean',revolve:'revolve',mesh:'mesh',delete:'trash'})[type]||'cube';
function toast(message,error=false){const el=document.createElement('div');el.className='toast'+(error?' error':'');el.textContent=message;$('#toast-region').append(el);setTimeout(()=>el.remove(),error?7500:3800);}
function status(text){$('#status-help').textContent=text;}
function download(data,name,type='application/octet-stream'){const blob=data instanceof Blob?data:new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
const filename=ext=>state.doc.name.replace(/[^\w .-]/g,'_')+'.'+ext;
function closeMenu(){$('#menu-layer').innerHTML='';}
function closeModal(){$('#modal-layer').innerHTML='';}
function modal(title,body,footer='<button class="primary-button" data-action="close-modal">Done</button>'){$('#modal-layer').innerHTML=`<div class="modal-scrim"><div class="modal" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="modal-header"><h2>${esc(title)}</h2><button class="icon-button" data-action="close-modal">${icon('close')}</button></div><div class="modal-body">${body}</div><div class="modal-footer">${footer}</div></div></div>`;}
function menu(anchor,items){closeMenu();const rect=anchor.getBoundingClientRect();const el=document.createElement('div');el.className='menu';el.style.left=Math.min(rect.left,innerWidth-240)+'px';el.style.top=Math.min(rect.bottom+5,innerHeight-items.length*35-30)+'px';el.innerHTML=items.map(item=>item==='-'?'<hr>':`<button data-command="${item[0]}">${icon(item[2]||commandMeta(item[0])[2])}<span>${esc(item[1])}</span>${item[3]?`<kbd>${esc(item[3])}</kbd>`:''}</button>`).join('');$('#menu-layer').append(el);}
function setTitle(){const title=state.doc.name;$('#title').innerHTML=`${esc(title)} <span class="version-label">v1</span>`;$('#tab-title').textContent=title;document.title=`${title} — Alloy Studio`;$('#viewport-caption').textContent=title==='Orbital bearing mount'?'ORBITAL / MECHANICAL ASSEMBLY':'ALLOY / PARAMETRIC DESIGN';}
function commit(label,mutate){state.history.push(state.doc,label);mutate(state.doc);state.doc.rollback=null;state.dirty=true;state.preview=false;state.selectedFeature=null;setTitle();scheduleSave();rebuild();}
function rebuild(documentOverride=null){revision++;pending={id:revision,document:clone(documentOverride||state.doc)};clearTimeout(rebuildTimer);rebuildTimer=setTimeout(dispatchWorker,15);$('#app').classList.add('busy');$('#save-state').innerHTML='<i></i> Regenerating';}
function dispatchWorker(){if(workerBusy||!pending)return;const request=pending;pending=null;workerBusy=true;clearTimeout(watchdog);watchdog=setTimeout(()=>{if(!workerBusy)return;worker?.terminate();workerBusy=false;createWorker();$('#app').classList.remove('busy');$('#loading').classList.add('hidden');toast('Modeling operation exceeded the safety timeout. Reduce the input geometry or undo the last feature.',true);},30000);if(worker)worker.postMessage(request);else setTimeout(()=>{try{workerResult({data:{id:request.id,result:new ModelEvaluator().evaluate(request.document)}});}catch(e){workerResult({data:{id:request.id,error:e.message}});}},0);}
function createWorker(){try{if(globalThis.__ALLOY_WORKER_SOURCE__){const url=URL.createObjectURL(new Blob([globalThis.__ALLOY_WORKER_SOURCE__],{type:'text/javascript'}));worker=new Worker(url);URL.revokeObjectURL(url);}else worker=new Worker(new URL('./worker.js',import.meta.url),{type:'module'});worker.onmessage=workerResult;worker.onerror=e=>{toast('Worker failed. Geometry will use the main-thread fallback.',true);worker.terminate();worker=null;workerBusy=false;clearTimeout(watchdog);rebuild();};}catch(e){worker=null;}}
function workerResult(event){workerBusy=false;clearTimeout(watchdog);const {id,result,error}=event.data;if(id!==revision){dispatchWorker();return;}$('#app').classList.remove('busy');if(error){toast(error,true);$('#loading').classList.add('hidden');$('#save-state').innerHTML='<i></i> Model error';return;}state.model=result;renderer.setScene(result.bodies);if(firstModel){renderer.camera.fit(renderer.bounds);firstModel=false;}if(state.selected&&!result.bodies.some(b=>b.id===state.selected)&&!result.sketches.some(s=>s.id===state.selected))state.selected=null;renderer.selected=state.selected;renderBrowser();renderTimeline();updateStats();$('#loading').classList.add('hidden');$('#save-state').innerHTML=`<i></i> ${state.preview?'Preview · not committed':saveLabel}`;if(state.form?.mode==='selection')showSelection();if(result.errors.length){toast(`${result.errors[0].name}: ${result.errors[0].message}`,true);}renderer.invalidate();state.ready=true;dispatchWorker();}
function updateStats(){const shown=state.model.bodies.filter(b=>b.visible),triangles=shown.reduce((s,b)=>s+b.mesh.stats.triangles,0);$('#mesh-stats').textContent=`${fmt(triangles,0)} triangles · ${shown.length} bodies`;$('#model-summary').textContent=`${state.doc.features.length} features · ${state.model.errors.length?'needs attention':'design history up to date'}`;$('#engine-badge').innerHTML=`<i></i> ${renderer.backend}`;$('#engine-badge').title=`${renderer.backend} · ${renderer.encodedMs.toFixed(2)} ms last CPU frame encode`;$('#undo-button').disabled=!state.history.undoStack.length;$('#redo-button').disabled=!state.history.redoStack.length;$('#view-label').textContent=(renderer.camera.ortho?'Orthographic':'Perspective')+' · '+(['shaded + edges','shaded','wireframe'][renderer.style]);}
async function initStorage(){try{db=await new Promise((resolve,reject)=>{const r=indexedDB.open('alloy-studio',1);r.onupgradeneeded=()=>r.result.createObjectStore('documents');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});const saved=await new Promise((resolve,reject)=>{const r=db.transaction('documents').objectStore('documents').get('autosave');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});if(saved){state.doc=validateDocument(saved);saveLabel='Restored from this device';setTitle();}}catch(e){db=null;saveLabel='Use File → Save';console.warn('Local persistence unavailable',e);}}
function scheduleSave(){
  const version=++saveVersion;clearTimeout(saveTimer);saveLabel=db?'Saving local copy…':'Use File → Save';
  saveTimer=setTimeout(()=>{
    if(!db){if(!workerBusy&&!state.preview)$('#save-state').innerHTML='<i></i> Use File → Save';return;}
    const failed=()=>{if(version!==saveVersion)return;saveLabel='Not saved · use File → Save';if(!workerBusy&&!state.preview)$('#save-state').innerHTML='<i></i> '+saveLabel;toast('Local autosave failed. Save a project file to keep your changes.',true);};
    try{const tx=db.transaction('documents','readwrite');tx.objectStore('documents').put(clone(state.doc),'autosave');tx.oncomplete=()=>{if(version!==saveVersion)return;saveLabel='Saved on this device';if(!workerBusy&&!state.preview)$('#save-state').innerHTML='<i></i> '+saveLabel;};tx.onerror=failed;tx.onabort=failed;}catch(e){failed();}
  },350);
}
function renderBrowser(){const filter=$('#browser-filter').value.toLowerCase();let html=`<div class="tree-row root" data-select="root"><span class="tree-arrow">▾</span>${icon('design')}<span class="tree-name">${esc(state.doc.name)}</span><span class="radio"></span></div><div class="tree-row folder" data-folder="settings"><span class="tree-arrow">${state.folders.settings?'▾':'▸'}</span>${icon('settings')}<span class="tree-name">Document settings</span></div>${state.folders.settings?'<div class="settings-row"><span>Units</span><span>Millimeters</span></div><div class="settings-row"><span>Modeling</span><span>Parametric</span></div>':''}<div class="tree-row folder" data-folder="origin"><span class="tree-arrow">${state.folders.origin?'▾':'▸'}</span>${icon('origin')}<span class="tree-name">Origin</span></div>${state.folders.origin?['XY','XZ','YZ'].map(p=>`<div class="tree-row child" data-plane="${p}">${icon('rectangle')}<span>${p} plane</span></div>`).join(''):''}<div class="tree-separator"></div><div class="tree-row folder" data-folder="bodies"><span class="tree-arrow">${state.folders.bodies?'▾':'▸'}</span>${icon('folder')}<span class="tree-name">Bodies</span><span class="tree-count">${state.model.bodies.length}</span></div>`;
  if(state.folders.bodies)for(const b of state.model.bodies){if(filter&&!b.name.toLowerCase().includes(filter))continue;const material=MATERIALS[b.material]||MATERIALS.aluminum,c=material.color.map(x=>Math.round(x*255));html+=`<div class="tree-row child ${state.selected===b.id?'active':''} ${b.visible?'':'hidden-body'}" data-body="${esc(b.id)}"><span class="material-dot" style="background:rgb(${c.join(',')})"></span>${icon('cube')}<span class="tree-name" title="${esc(b.name)}">${esc(b.name)}</span><button class="eye" data-toggle-body="${esc(b.id)}" title="Toggle visibility">${icon(b.visible?'eye':'eye-off')}</button></div>`;}
  html+=`<div class="tree-row folder" data-folder="sketches"><span class="tree-arrow">${state.folders.sketches?'▾':'▸'}</span>${icon('folder')}<span class="tree-name">Sketches</span><span class="tree-count">${state.model.sketches.length}</span></div>`;
  if(state.folders.sketches)for(const s of state.model.sketches)html+=`<div class="tree-row child ${state.selected===s.id?'active':''}" data-sketch="${esc(s.id)}">${icon('sketch')}<span class="tree-name">${esc(s.name)}</span></div>`;
  if(state.model.errors.length)html+=`<div class="tree-separator"></div><div class="error-list">${state.model.errors.map(e=>`<p><strong>${esc(e.name)}</strong><br>${esc(e.message)}</p>`).join('')}</div>`;
  $('#browser-tree').innerHTML=html;
}
function renderTimeline(){const states=new Map(state.model.timeline.map(x=>[x.id,x.state]));let html='';state.doc.features.forEach((f,i)=>{html+=`<button class="timeline-feature ${state.selectedFeature===f.id?'active':''} ${states.get(f.id)||''} ${state.doc.rollback!==null&&i>state.doc.rollback?'rolled-back':''}" data-feature="${esc(f.id)}" data-type="${f.type}" title="${i+1}. ${esc(f.name)} · click to edit; right-click for history options">${icon(featureIcon(f.type))}</button>`;if(state.doc.rollback===i)html+='<span class="timeline-end"></span>';});if(state.doc.rollback===null)html+='<span class="timeline-end"></span>';$('#timeline').innerHTML=html;$('#history-caption').textContent=state.doc.rollback===null?`${state.doc.features.length} features · full history`:`Rolled back to feature ${state.doc.rollback+1}`;}
function tool(id,label=null){const m=commandMeta(id);return `<button class="tool-button ${state.sketch?.tool===id?'active':''}" data-command="${id}" title="${esc(m[1])}${m[3]?' · '+m[3]:''}">${icon(m[2])}<span>${esc(label||m[1])}</span></button>`;}
function group(label,tools){return `<div class="ribbon-group">${tools.map(t=>Array.isArray(t)?tool(...t):tool(t)).join('')}<div class="group-label">${label}<span>⌄</span></div></div>`;}
function renderRibbon(){let html='';if(state.sketch){html=group('CREATE',[['rectangle','Rectangle'],['circle','Circle'],['polygon','Polyline']])+group('EDIT',[['sketch-undo','Undo profile'],['sketch-clear','Clear sketch']])+group('CONSTRAINTS',[['sketch-snap','Grid snap']])+group('FINISH',[['finish-sketch','Finish sketch']]);}
  else if(state.tab==='solid')html=group('CREATE',[['create-sketch','Create sketch'],['extrude','Extrude'],['revolve','Revolve'],['box','Box'],['cylinder','Cylinder']])+group('MODIFY',[['hole','Hole'],['boolean','Combine'],['move','Move']])+group('ASSEMBLE',[['pattern','Pattern']])+group('APPEARANCE',[['appearance','Appearance']])+group('INSPECT',[['measure','Measure'],['section','Section']])+group('MANAGE',[['parameters','Parameters']]);
  else if(state.tab==='sketch')html=group('SKETCH',[['create-sketch','Create sketch']])+group('CREATE SOLID',[['extrude','Extrude'],['revolve','Revolve']])+group('MANAGE',[['parameters','Parameters'],['show-sketches','Show sketches']]);
  else if(state.tab==='mesh')html=group('INSERT',[['import','Import mesh']])+group('PRIMITIVES',[['box','Box'],['cylinder','Cylinder'],['sphere','Sphere'],['torus','Torus']])+group('MODIFY',[['boolean','Combine'],['move','Move'],['pattern','Pattern']])+group('EXPORT',[['export-stl','Export STL'],['export-obj','Export OBJ']]);
  else if(state.tab==='inspect')html=group('ANALYZE',[['measure','Measure'],['section','Section'],['diagnostics','Diagnostics']])+group('DESIGN INTENT',[['parameters','Parameters']])+group('DOCUMENT',[['drawing','Drawing'],['screenshot','Capture PNG']]);
  else html=group('NAVIGATE',[['home','Home'],['fit','Fit'],['projection','Projection']])+group('DISPLAY',[['view-options','Display'],['grid','Grid'],['appearance','Appearance'],['explode','Explode']])+group('DOCUMENT',[['screenshot','Capture PNG'],['drawing','Drawing']]);
  $('#ribbon').innerHTML=html;$$('#mode-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===(state.sketch?'sketch':state.tab)));
}
// Keep command metadata for sketch and display tools in the same palette/toolbar path.
commands.push(['rectangle','Rectangle','rectangle','R'],['circle','Circle','circle','C'],['polygon','Polyline','polygon','L'],['sketch-undo','Undo last profile','undo',''],['sketch-clear','Clear sketch','trash',''],['sketch-snap','Toggle grid snap','grid',''],['finish-sketch','Finish sketch','check',''],['show-sketches','Show sketch profiles','sketch',''],['view-options','Display settings','display','']);
function panel(title,content,footer=''){const p=$('#inspector');p.classList.remove('hidden');p.innerHTML=`<div class="pane-heading"><span>${esc(title.toUpperCase())}</span><button class="icon-button small" data-action="close-inspector">${icon('close')}</button></div><div class="inspector-content">${content}</div>${footer?`<div class="inspector-footer">${footer}</div>`:''}`;renderer.invalidate();}
function closeInspector(){if(state.preview){state.preview=false;rebuild();}if(state.sketch)return;state.form=null;$('#inspector').classList.add('hidden');renderer.invalidate();}
function field(name,label,value='',options=null){return `<label class="field"><span>${esc(label)}</span>${options?`<select name="${name}">${options.map(o=>{const [v,l]=Array.isArray(o)?o:[o,o];return `<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`;}).join('')}</select>`:`<input name="${name}" value="${esc(value)}" autocomplete="off" spellcheck="false">`}</label>`;}
const parameterFields={
 box:[['width','Width',60],['depth','Depth',40],['height','Height',20],['radius','Corner radius',2]],
 cylinder:[['radius','Radius',20],['height','Height',30],['segments','Segments',64]],sphere:[['radius','Radius',25]],torus:[['major','Major radius',30],['minor','Minor radius',8]],
 extrude:[['distance','Distance',20]],revolve:[['angle','Angle (degrees)',360]],
 hole:[['radius','Hole radius',5],['depth','Cut depth',100],['counterbore','Counterbore radius',0],['counterdepth','Counterbore depth',0]],
 move:[['x','Translate X',0],['y','Translate Y',0],['z','Translate Z',0],['rx','Rotate X (°)',0],['ry','Rotate Y (°)',0],['rz','Rotate Z (°)',0],['scale','Uniform scale',1]],
 pattern:[['count','Total instances',3],['spacing','Spacing',50],['angle','Total angle (°)',360]],
 sketch:[['width','Width',40],['height','Height',30],['radius','Radius',0]],boolean:[],mesh:[]
};
function selectedBody(){return state.model.bodies.find(b=>b.id===state.selected);}
function select(id,open=true){state.selected=id;state.selectedFeature=null;renderer.selected=id;renderBrowser();renderTimeline();renderer.invalidate();if(open){const b=selectedBody();if(b)showSelection();else if(id){const f=state.doc.features.find(f=>f.id===id);if(f?.type==='sketch')openFeature('sketch',f);}else closeInspector();}}
function showSelection(){const b=selectedBody();if(!b)return;state.form={mode:'selection'};const s=b.mesh.stats,material=MATERIALS[b.material]||MATERIALS.aluminum,size=s.bounds.max.map((v,i)=>v-s.bounds.min[i]);panel('Body properties',`<h2 class="inspector-title">${esc(b.name)}</h2><div class="inspector-subtitle">Solid mesh body · ${esc(material.name)}</div><label class="field full"><span>Body name</span><input id="rename-body" value="${esc(b.name)}"></label><div class="body-actions"><button class="secondary-button" data-command="move">${icon('move')}Move</button><button class="secondary-button" data-action="edit-source">${icon('edit')}Edit feature</button></div><div class="form-section">Physical properties · approximate</div>${[['Volume',`${fmt(s.volume/1000,3)} cm³`],['Surface area',`${fmt(s.area/100,2)} cm²`],['Mass',`${fmt(s.volume/1000*material.density,2)} g`],['Bounds X',`${fmt(size[0])} mm`],['Bounds Y',`${fmt(size[1])} mm`],['Bounds Z',`${fmt(size[2])} mm`],['Triangles',fmt(s.triangles,0)]].map(([k,v])=>`<div class="inspect-stat"><span>${k}</span><strong>${v}</strong></div>`).join('')}<div class="form-section">Appearance</div>${materialGrid(b.material)}<div class="form-help">Click a material to apply it. Physical properties are computed from the tessellated boundary, not an analytic CAD solid.</div>`,`<button class="secondary-button" data-command="export-stl">Export STL</button><button class="danger-button" data-command="delete">Delete</button>`);}
function materialGrid(selected){return `<div class="material-grid">${Object.entries(MATERIALS).map(([k,m])=>`<button class="material-card ${selected===k?'active':''}" data-material="${k}"><span class="material-sphere" style="background:rgb(${m.color.map(v=>v*255).join(',')})"></span><span>${esc(m.name)}</span></button>`).join('')}</div>`;}
function openFeature(type,existing=null){
  if(state.sketch){toast('Finish the current sketch first.');return;}if(state.preview){state.preview=false;rebuild();}
  const selected=selectedBody();const requires=['hole','move','pattern','boolean'];if(!existing&&requires.includes(type)&&!selected){const first=state.model.bodies.find(b=>b.visible);if(!first){toast('Create or select a body first.',true);return;}state.selected=first.id;renderer.selected=first.id;}
  const feature=existing?clone(existing):{id:uid(),type,name:({box:'Box',cylinder:'Cylinder',sphere:'Sphere',torus:'Torus',extrude:'Extrude',revolve:'Revolve',hole:'Hole',move:'Move body',pattern:'Pattern',boolean:'Combine'})[type]||'Sketch',p:{},...(['box','cylinder','sphere','torus','extrude','revolve'].includes(type)?{material:'aluminum'}:{})};
  if(!existing&&requires.includes(type))feature.target=state.selected;
  if(!existing&&(type==='extrude'||type==='revolve')){const s=state.model.sketches.find(s=>s.id===state.selected)||state.model.sketches.at(-1);if(!s){toast('Draw and finish a closed sketch profile first.');startSketch();return;}feature.profile=s.id;}
  state.form={mode:'feature',type,feature,existing:!!existing};state.selectedFeature=existing?.id||null;
  let content=`<h2 class="inspector-title">${existing?'Edit ':''}${esc(({boolean:'Combine',move:'Move / copy',pattern:'Pattern'})[type]||type[0].toUpperCase()+type.slice(1))}</h2><div class="inspector-subtitle">${existing?'Edit this feature to regenerate dependent geometry.':'Create a parametric feature in your design history.'}</div><form id="feature-form"><label class="field full"><span>Feature name</span><input name="_name" value="${esc(feature.name)}"></label>`;
  if(requires.includes(type))content+=field('_target','Target body',feature.target,state.model.bodies.map(b=>[b.id,b.name]).concat(existing&&!state.model.bodies.some(b=>b.id===feature.target)?[[feature.target,'Original input body']]:[]));
  if(['extrude','revolve'].includes(type))content+=field('_profile','Sketch profile',feature.profile,state.model.sketches.map(s=>[s.id,s.name]));
  if(type==='boolean'){const tool=feature.tool||state.model.bodies.find(b=>b.id!==feature.target)?.id;content+=field('_tool','Tool body',tool,state.model.bodies.filter(b=>b.id!==feature.target).map(b=>[b.id,b.name]).concat(existing&&!state.model.bodies.some(b=>b.id===feature.tool)?[[feature.tool,'Original tool body']]:[]));content+=field('operation','Operation',feature.p.operation||'union',[['union','Join'],['cut','Cut'],['intersect','Intersect']]);content+=`<label class="toggle-row">Keep tool body<input type="checkbox" name="keepTool" ${feature.p.keepTool?'checked':''}></label>`;}
  content+='<div class="form-section">Dimensions</div>';
  let fields=parameterFields[type]||[];if(type==='sketch'){content+=field('plane','Sketch plane',feature.p.plane||'XY',['XY','XZ','YZ']);if(feature.p.shape==='circle')fields=[['radius','Radius',20]];else if(feature.p.shape==='polygon')fields=[];else fields=[['width','Width',40],['height','Height',30],['radius','Corner radius',0]];}
  for(const [name,label,value] of fields)content+=field(name,label,feature.p[name]??value);
  if(type==='hole'||type==='pattern')content+=field('axis',type==='hole'?'Drill axis':'Pattern axis',feature.p.axis|| (type==='hole'?'Z':'X'),['X','Y','Z']);
  if(type==='pattern')content+=`<label class="toggle-row">Circular around world Z<input type="checkbox" name="circular" ${feature.p.circular?'checked':''}></label>`;
  if(!['move','pattern','boolean','extrude','revolve'].includes(type)){content+='<div class="form-section">Position · millimeters</div>';for(const name of ['x','y','z'])content+=field(name,name.toUpperCase(),feature.p[name]??0);if(['box','cylinder','sphere','torus','mesh'].includes(type)){content+='<details><summary>Rotation and scale</summary>';for(const [name,label,def] of [['rx','Rotation X (°)',0],['ry','Rotation Y (°)',0],['rz','Rotation Z (°)',0],['scale','Scale',1]])content+=field(name,label,feature.p[name]??def);content+='</details>';}}
  if(['box','cylinder','sphere','torus','extrude','revolve'].includes(type))content+=field('_material','Appearance',feature.material||'aluminum',Object.entries(MATERIALS).map(([k,v])=>[k,v.name]));
  if(type==='sketch'&&feature.p.shape==='polygon')content+=`<label class="field full"><span>Profile vertices · [x, y] per line</span><textarea name="_points" rows="8" style="width:100%;border:1px solid #dce5eb;border-radius:4px;padding:7px;font-family:monospace;font-size:10px">${feature.p.points.map(p=>p.join(', ')).join('\n')}</textarea></label>`;
  content+='</form><div id="form-error"></div><div class="form-help">Inputs accept parameters and arithmetic: <code>baseWidth / 2</code>, <code>2 * cm</code>. Angles use degrees; lengths use millimeters.</div>';
  if(existing)content+=`<div class="feature-index">Feature ${state.doc.features.findIndex(f=>f.id===existing.id)+1} of ${state.doc.features.length}</div>`;
  panel('Feature editor',content,'<button class="secondary-button" data-action="preview-feature">Preview</button><button class="secondary-button" data-action="close-inspector">Cancel</button><button class="primary-button" data-action="apply-feature">Apply</button>');renderTimeline();renderer.invalidate();
}
function readFeature(){const f=clone(state.form.feature),form=$('#feature-form'),data=new FormData(form);for(const [name,value] of data){if(name==='_name')f.name=String(value).trim()||f.type;else if(name==='_target')f.target=value;else if(name==='_tool')f.tool=value;else if(name==='_profile')f.profile=value;else if(name==='_material')f.material=value;else if(name==='_points'){f.p.points=String(value).trim().split(/\n/).map(line=>{const p=line.split(',').map(v=>v.trim());if(p.length!==2)throw Error('Each vertex needs two comma-separated coordinates.');return p;});}else if(!['keepTool','circular'].includes(name))f.p[name]=value;}
  for(const n of ['keepTool','circular'])if(form.elements[n])f.p[n]=form.elements[n].checked;
  const env=parameters(state.doc.parameters),stringProps=['plane','axis','operation','shape','points','faces'];for(const [k,v] of Object.entries(f.p)){if(typeof v==='string'&&!stringProps.includes(k))expression(v,name=>{if(!Object.hasOwn(env,name))throw Error('Unknown parameter: '+name);return env[name];});}
  return f;
}
function applyFeature(preview=false){try{const f=readFeature(),edit=state.form.existing;if(preview){const d=clone(state.doc);if(edit)d.features[d.features.findIndex(x=>x.id===f.id)]=f;else d.features.push(f);d.rollback=null;state.preview=true;rebuild(d);$('#form-error').innerHTML='<div class="preview-banner">Preview only — Apply to keep this change.</div>';return;}commit(edit?'Edit '+f.name:'Create '+f.name,d=>{if(edit)d.features[d.features.findIndex(x=>x.id===f.id)]=f;else d.features.push(f);});state.selected=f.type==='pattern'?f.id+':1':f.id;renderer.selected=state.selected;state.form=null;$('#inspector').classList.add('hidden');toast(f.name+(edit?' updated.':' created.'));}catch(e){$('#form-error').innerHTML=`<div class="form-error">${esc(e.message)}</div>`;}}
function startSketch(plane='XY'){
  if(state.sketch)return;if(state.preview){state.preview=false;rebuild();}
  state.sketch={plane,tool:'rectangle',profiles:[],points:[],start:null,current:null,snap:true,spacing:1};state.form={mode:'sketch'};state.measure=null;state.selected=null;renderer.selected=null;renderer.camera.ortho=true;renderer.camera.setView(plane==='XY'?'top':plane==='XZ'?'front':'right');renderer.camera.target=[0,0,0];renderer.camera.distance=Math.max(160,renderer.camera.distance);$('#app').classList.add('sketch-mode');$('#sketch-footer').classList.remove('hidden');renderRibbon();showSketchPalette();renderer.invalidate();toast('Sketch on '+plane+' plane. Drag to draw; dimensions are editable.');
}
function showSketchPalette(){const s=state.sketch;if(!s)return;const p=s.profiles.at(-1);panel('Sketch palette',`<h2 class="inspector-title">Sketch ${state.model.sketches.length+1}</h2><div class="inspector-subtitle">${s.plane} origin plane · closed profiles</div><div class="form-section">Drawing settings</div>${field('sketch-plane','Plane',s.plane,['XY','XZ','YZ'])}<label class="toggle-row">Snap to grid<input type="checkbox" id="sketch-snap" ${s.snap?'checked':''}></label>${field('sketch-spacing','Grid step (mm)',s.spacing)}<div class="inspect-stat"><span>Closed profiles</span><strong>${s.profiles.length}</strong></div>${p?`<div class="form-section">Last profile dimensions</div><div id="last-profile-fields">${p.shape==='rectangle'?field('profile-width','Width',p.width)+field('profile-height','Height',p.height):p.shape==='circle'?field('profile-radius','Radius',p.radius):'<div class="notice">'+p.points.length+' polygon vertices. Edit exact vertex coordinates from the timeline after finishing.</div>'}</div>`:''}<div class="form-help">Rectangle and circle: drag from the first point.<br><br>Polyline: click vertices; click the start point or press Enter to close. Shift constrains rectangle proportions and polygon direction.<br><br>Profiles are independent loops. Create holes using a separate Cut feature.</div>`,'<button class="secondary-button" data-action="cancel-sketch">Cancel</button><button class="primary-button" data-command="finish-sketch">Finish sketch</button>');$('#sketch-hint').textContent=s.tool==='rectangle'?'Drag to draw a rectangle':s.tool==='circle'?'Drag to draw a circle':'Click vertices · Enter to close';}
function finishSketch(){if(!state.sketch)return;closePolygon();const s=state.sketch;if(!s.profiles.length){toast('Draw a closed profile before finishing.');return;}const features=s.profiles.map((p,i)=>({id:uid('sk'),type:'sketch',name:`Sketch ${state.model.sketches.length+i+1}`,p:{...clone(p),plane:s.plane}}));state.sketch=null;$('#app').classList.remove('sketch-mode');$('#sketch-footer').classList.add('hidden');$('#inspector').classList.add('hidden');state.form=null;state.tab='solid';state.folders.sketches=true;commit('Create sketch',d=>d.features.push(...features));state.selected=features.at(-1).id;renderer.camera.setView('iso');renderer.selected=null;renderRibbon();toast('Sketch saved. Press E to extrude the selected profile.');}
function cancelSketch(){state.sketch=null;$('#app').classList.remove('sketch-mode');$('#sketch-footer').classList.add('hidden');$('#inspector').classList.add('hidden');state.form=null;renderer.camera.setView('iso');renderRibbon();renderer.invalidate();}
function planePoint(x,y){const s=state.sketch,ray=renderer.camera.ray(x,y),axis=s.plane==='XY'?2:s.plane==='XZ'?1:0;if(Math.abs(ray.d[axis])<1e-9)return null;const p=V.add(ray.o,V.mul(ray.d,-ray.o[axis]/ray.d[axis]));let uv=s.plane==='XY'?[p[0],p[1]]:s.plane==='XZ'?[p[0],p[2]]:[-p[2],p[1]];if(s.snap)uv=uv.map(v=>Math.round(v/s.spacing)*s.spacing);return uv;}
function uvWorld(uv,plane,origin=[0,0,0]){return V.add(plane==='XY'?[uv[0],uv[1],0]:plane==='XZ'?[uv[0],0,uv[1]]:[0,uv[1],-uv[0]],origin);}
function profilePoints(p){if(p.shape==='rectangle')return rectangle(Number(p.width),Number(p.height),Number(p.radius||0));if(p.shape==='circle')return circle(Number(p.radius));return p.points;}
function draftProfile(a,b,shift=false){const s=state.sketch;if(!a||!b)return null;let dx=b[0]-a[0],dy=b[1]-a[1];if(shift&&s.tool==='rectangle'){const m=Math.max(Math.abs(dx),Math.abs(dy));dx=Math.sign(dx||1)*m;dy=Math.sign(dy||1)*m;}if(s.tool==='circle'){const r=Math.hypot(dx,dy);if(r<.01)return null;const c=uvWorld(a,s.plane);return {shape:'circle',radius:+r.toFixed(3),x:c[0],y:c[1],z:c[2]};}if(Math.abs(dx)<.01||Math.abs(dy)<.01)return null;const c=uvWorld([a[0]+dx/2,a[1]+dy/2],s.plane);return {shape:'rectangle',width:+Math.abs(dx).toFixed(3),height:+Math.abs(dy).toFixed(3),radius:0,x:c[0],y:c[1],z:c[2]};}
function closePolygon(){const s=state.sketch;if(!s||s.points.length<3)return;const p={shape:'polygon',points:clone(s.points),x:0,y:0,z:0};s.profiles.push(p);s.points=[];s.current=null;showSketchPalette();renderer.invalidate();}
function drawOverlay(){const canvas=$('#overlay'),stage=$('#stage'),r=stage.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(r.width*dpr)||canvas.height!==Math.round(r.height*dpr)){canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,r.width,r.height);const project=p=>renderer.camera.project(p);
  const path=(points,color,width=1,fill=null,closed=true)=>{if(!points.length)return;ctx.beginPath();points.forEach((p,i)=>{const q=project(p);if(i)ctx.lineTo(q[0],q[1]);else ctx.moveTo(q[0],q[1]);});if(closed)ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill();}ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();};
  if(state.sketch){const s=state.sketch,span=renderer.camera.distance*.8,step=Math.max(s.spacing,Math.pow(10,Math.floor(Math.log10(span/35))))*1;ctx.lineWidth=.6;for(let i=-Math.ceil(span/step);i<=Math.ceil(span/step);i++){const p=i*step;path([uvWorld([p,-span],s.plane),uvWorld([p,span],s.plane)],i===0?'#829dac':'#bdcbd754',i===0?1:.6,null,false);path([uvWorld([-span,p],s.plane),uvWorld([span,p],s.plane)],i===0?'#a8958c':'#bdcbd754',i===0?1:.6,null,false);}
    for(const p of s.profiles)path(profilePoints(p).map(q=>uvWorld(q,s.plane,[p.x||0,p.y||0,p.z||0])),'#277f9f',1.5,'#3e99b81c');
    if(s.start&&s.current){const p=draftProfile(s.start,s.current,s.shift);if(p){const points=profilePoints(p).map(q=>uvWorld(q,s.plane,[p.x,p.y,p.z]));path(points,'#1780ab',1.7,'#51acd51a');const q=project(uvWorld(s.current,s.plane));const label=p.shape==='rectangle'?`${fmt(p.width)} × ${fmt(p.height)} mm`:`R ${fmt(p.radius)} mm`;ctx.font='11px system-ui';const tw=ctx.measureText(label).width;ctx.fillStyle='#fff';ctx.fillRect(q[0]+13,q[1]-28,tw+16,25);ctx.strokeStyle='#c4dae5';ctx.strokeRect(q[0]+13,q[1]-28,tw+16,25);ctx.fillStyle='#41758e';ctx.fillText(label,q[0]+21,q[1]-11);}}
    if(s.points.length){const points=s.points.map(q=>uvWorld(q,s.plane));if(s.current)points.push(uvWorld(s.current,s.plane));path(points,'#287fa1',1.5,null,false);for(const p of s.points){const q=project(uvWorld(p,s.plane));ctx.beginPath();ctx.arc(q[0],q[1],3.5,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle='#287fa1';ctx.stroke();}}
  }
  if(!state.sketch)for(const sk of state.model.sketches){if(state.showSketches||state.selected===sk.id)path(sk.points.map(p=>uvWorld(p,sk.plane,sk.origin)),'#307fa4',1.7,state.selected===sk.id?'#419aca15':null);}
  if(state.measure){const points=state.measure.points;for(const p of points){const q=project(p);ctx.beginPath();ctx.arc(q[0],q[1],4,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle='#2287b7';ctx.lineWidth=2;ctx.stroke();}if(points.length===2){const a=project(points[0]),b=project(points[1]);ctx.setLineDash([4,3]);path(points,'#287fa1',1.5,null,false);ctx.setLineDash([]);const label=fmt(V.distance(...points),3)+' mm',x=(a[0]+b[0])/2,y=(a[1]+b[1])/2;ctx.font='12px system-ui';const w=ctx.measureText(label).width;ctx.fillStyle='#fff';ctx.fillRect(x-w/2-9,y-28,w+18,25);ctx.fillStyle='#37738f';ctx.fillText(label,x-w/2,y-11);}}
  if(state.form?.type==='move'&&selectedBody()){const b=selectedBody(),origin=V.mul(V.add(b.mesh.stats.bounds.min,b.mesh.stats.bounds.max),.5),size=renderer.camera.distance*.075;state.gizmoAxes=[];for(let i=0;i<3;i++){const end=origin.slice();end[i]+=size;const a=project(origin),e=project(end),color=['#c07766','#71a083','#6199bc'][i];path([origin,end],color,2.5,null,false);ctx.beginPath();ctx.arc(e[0],e[1],4,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();ctx.font='11px system-ui';ctx.fillText('XYZ'[i],e[0]+7,e[1]+3);state.gizmoAxes.push({axis:'xyz'[i],a:a.slice(0,2),b:e.slice(0,2),worldLength:size});}}else state.gizmoAxes=[];
  const center=project(renderer.camera.target),axes=[[1,0,0],[0,1,0],[0,0,1]],colors=['#bd7a70','#75a58d','#6e9fbd'];$('#axis-triad').innerHTML=`<svg viewBox="0 0 62 62">${axes.map((axis,i)=>{const p=project(V.add(renderer.camera.target,V.mul(axis,renderer.camera.distance*.03))),x=31+(p[0]-center[0]),y=32+(p[1]-center[1]);return `<line x1="31" y1="32" x2="${x}" y2="${y}" stroke="${colors[i]}" stroke-width="1.5"/><text x="${x+4}" y="${y-3}" fill="${colors[i]}" stroke="none" font-family="Arial" font-size="10">${'XYZ'[i]}</text>`;}).join('')}<circle cx="31" cy="32" r="2" fill="#a2b2be" stroke="none"/></svg>`;
}
function pick(x,y){const ray=renderer.camera.ray(x,y);let best=null;for(const b of state.model.bodies){if(!b.visible)continue;const offset=renderer.offset(b),local={o:V.sub(ray.o,offset),d:ray.d},axis={X:0,Y:1,Z:2}[renderer.section.axis];const hit=pickMesh(local,b.mesh,h=>!renderer.section.enabled||h.point[axis]+offset[axis]<=renderer.section.offset);if(hit&&(!best||hit.distance<best.distance))best={...hit,point:V.add(hit.point,offset),body:b};}return best;}
let pointer=null,lastHoverAt=0;
function bindViewport(){const overlay=$('#overlay'),pos=e=>{const r=overlay.getBoundingClientRect();return [e.clientX-r.left,e.clientY-r.top];};overlay.addEventListener('contextmenu',e=>e.preventDefault());overlay.addEventListener('pointerdown',e=>{if(e.button>2)return;closeMenu();$('#stage').focus();const [x,y]=pos(e);overlay.setPointerCapture(e.pointerId);pointer={x,y,lastX:x,lastY:y,button:e.button,moved:0,mode:e.button===1?(e.shiftKey?'orbit':'pan'):e.button===2||e.altKey?'orbit':state.nav==='orbit'?'orbit':state.nav==='pan'?'pan':'select'};if(e.button===0&&state.sketch){pointer.mode='sketch';const p=planePoint(x,y);if(state.sketch.tool==='polygon'){const s=state.sketch;if(s.points.length>2){const first=renderer.camera.project(uvWorld(s.points[0],s.plane));if(Math.hypot(first[0]-x,first[1]-y)<12){closePolygon();pointer=null;return;}}if(p)s.points.push(p);}else state.sketch.start=p;state.sketch.current=p;renderer.invalidate();return;}
    if(e.button===0&&state.gizmoAxes?.length){for(const axis of state.gizmoAxes){const ab=[axis.b[0]-axis.a[0],axis.b[1]-axis.a[1]],len2=ab[0]**2+ab[1]**2,t=clamp(((x-axis.a[0])*ab[0]+(y-axis.a[1])*ab[1])/len2,0,1),distance=Math.hypot(x-axis.a[0]-t*ab[0],y-axis.a[1]-t*ab[1]);if(distance<8&&len2>4){pointer.mode='gizmo';pointer.axis=axis;pointer.initial=Number($('#feature-form').elements[axis.axis].value)||0;break;}}}
  });overlay.addEventListener('pointermove',e=>{const [x,y]=pos(e);if(state.sketch){let p=planePoint(x,y);const s=state.sketch;if(e.shiftKey&&s.tool==='polygon'&&s.points.length&&p){const a=s.points.at(-1),dx=p[0]-a[0],dy=p[1]-a[1],angle=Math.round(Math.atan2(dy,dx)/(Math.PI/4))*Math.PI/4,len=Math.hypot(dx,dy);p=[a[0]+Math.cos(angle)*len,a[1]+Math.sin(angle)*len];}s.current=p;s.shift=e.shiftKey;renderer.invalidate();if(p)status(`Sketch ${s.plane} · X ${fmt(p[0])} mm · Y ${fmt(p[1])} mm${s.snap?' · Grid snap on':''}`);}
    if(pointer){const dx=x-pointer.lastX,dy=y-pointer.lastY;pointer.moved+=Math.hypot(dx,dy);pointer.lastX=x;pointer.lastY=y;if(pointer.mode==='orbit'){renderer.camera.yaw-=dx*.007;renderer.camera.pitch=clamp(renderer.camera.pitch+dy*.007,-Math.PI/2+.0001,Math.PI/2-.0001);renderer.invalidate();}else if(pointer.mode==='pan'){renderer.camera.pan(dx,dy);renderer.invalidate();}else if(pointer.mode==='gizmo'){const a=pointer.axis,ab=[a.b[0]-a.a[0],a.b[1]-a.a[1]],units=((x-pointer.x)*ab[0]+(y-pointer.y)*ab[1])/(ab[0]**2+ab[1]**2)*a.worldLength;$('#feature-form').elements[a.axis].value=+(pointer.initial+units).toFixed(2);clearTimeout(hoverTimer);hoverTimer=setTimeout(()=>applyFeature(true),65);}return;}
    if(!state.sketch&&performance.now()-lastHoverAt>55){lastHoverAt=performance.now();const hit=pick(x,y);if(renderer.hover!==hit?.body.id){renderer.hover=hit?.body.id||null;renderer.invalidate();}overlay.style.cursor=hit?'pointer':'default';}
  });overlay.addEventListener('pointerup',e=>{if(!pointer)return;const p=pointer;pointer=null;const [x,y]=pos(e);if(p.mode==='sketch'){const s=state.sketch;if(s?.tool!=='polygon'){const profile=draftProfile(s.start,s.current,e.shiftKey);if(profile)s.profiles.push(profile);s.start=null;s.current=null;showSketchPalette();renderer.invalidate();}return;}if(p.mode==='gizmo'){clearTimeout(hoverTimer);applyFeature(true);return;}if(p.moved<5&&p.button===0&&p.mode==='select'){const hit=pick(x,y);if(state.measure){if(hit){if(state.measure.points.length>=2)state.measure.points=[];state.measure.points.push(hit.point);showMeasure();renderer.invalidate();}else toast('Pick a point on a visible body.');}else select(hit?.body.id||null);}});
  overlay.addEventListener('pointercancel',()=>{pointer=null;if(state.sketch)state.sketch.start=null;});overlay.addEventListener('dblclick',e=>{if(state.sketch?.tool==='polygon'){if(state.sketch.points.length>1&&V.distance([...state.sketch.points.at(-1),0],[...state.sketch.points.at(-2),0])<.001)state.sketch.points.pop();closePolygon();}else if(!state.sketch&&!state.measure)command('fit');});overlay.addEventListener('wheel',e=>{e.preventDefault();const [x,y]=pos(e);renderer.camera.zoom(clamp(e.deltaY,-180,180),x,y);renderer.invalidate();},{passive:false});
}
function showMeasure(){state.form={mode:'measure'};const ps=state.measure.points;panel('Measure',`<h2 class="inspector-title">Point-to-point</h2><div class="inspector-subtitle">Pick two visible surface points in the viewport.</div>${ps.length===2?`<div class="measure-result">${fmt(V.distance(...ps),3)}<small>mm</small></div>${['X','Y','Z'].map((k,i)=>`<div class="inspect-stat"><span>Δ${k}</span><strong>${fmt(ps[1][i]-ps[0][i],3)} mm</strong></div>`).join('')}`:`<div class="notice">${ps.length?'First point selected. Pick the second point.':'Click a surface to set the first point.'}</div>`}${ps.map((p,i)=>`<div class="form-section">Point ${i+1}</div><div class="small-note">${p.map(v=>fmt(v,3)).join(', ')} mm</div>`).join('')}<div class="form-help">Points lie on tessellated triangles. This is a spatial distance, not an analytic edge or radius measurement.</div>`,'<button class="secondary-button" data-action="reset-measure">Reset</button><button class="primary-button" data-action="finish-measure">Done</button>');}
function showSection(){state.form={mode:'section'};const s=renderer.section,b=renderer.bounds||{min:[-100,-100,0],max:[100,100,100]},axis={X:0,Y:1,Z:2}[s.axis];panel('Section analysis',`<h2 class="inspector-title">Look inside</h2><div class="inspector-subtitle">Non-destructive clipping plane.</div><label class="toggle-row">Enable section<input type="checkbox" id="section-enabled" ${s.enabled?'checked':''}></label>${field('section-axis','Plane normal',s.axis,['X','Y','Z'])}${field('section-offset','Offset (mm)',s.offset)}<input type="range" id="section-slider" min="${b.min[axis]-1}" max="${b.max[axis]+1}" step=".1" value="${s.offset}"><div class="form-help">Drag the plane through the assembly. This is an uncapped visual section; exports retain the original solid geometry.</div>`,'<button class="primary-button" data-action="close-inspector">Done</button>');}
function viewOptions(){state.form={mode:'view'};panel('Display settings',`<h2 class="inspector-title">Your perspective</h2><div class="inspector-subtitle">Viewport and presentation settings.</div><div class="form-section">Visual style</div><div class="view-options-list">${[['Shaded with edges','cube'],['Shaded','sphere'],['Wireframe','mesh']].map(([name,ic],i)=>`<button data-style="${i}" class="${renderer.style===i?'active':''}">${icon(ic)}${name}</button>`).join('')}</div><label class="toggle-row">Perspective camera<input type="checkbox" id="perspective-setting" ${renderer.camera.ortho?'':'checked'}></label><label class="toggle-row">Layout grid<input type="checkbox" id="grid-setting" ${renderer.grid?'checked':''}></label><label class="toggle-row">Show sketch profiles<input type="checkbox" id="show-sketches-setting" ${state.showSketches?'checked':''}></label><div class="form-section">Exploded presentation</div><input id="explode-slider" type="range" min="0" max="2" step=".02" value="${renderer.explode}"><div class="small-note">${Math.round(renderer.explode*100)}% displacement · presentation only</div><div class="form-help">${renderer.backend==='WebGPU'?'Native WebGPU · 4× MSAA · GGX direct lighting · shadow mapping.':'WebGL2 compatibility renderer · analytic studio lighting.'}<br><br>Frames are rendered on demand; the GPU stays idle when the design is unchanged.</div>`,'<button class="primary-button" data-action="close-inspector">Done</button>');}
function showParameters(){const rows=Object.entries(state.doc.parameters).map(([k,v])=>parameterRow(k,v)).join('');modal('User parameters',`<p>Give dimensions a name. Dependent features regenerate when a value changes.</p><table class="parameters-table"><thead><tr><th>NAME</th><th>EXPRESSION</th><th>VALUE</th><th></th></tr></thead><tbody id="parameter-rows">${rows}</tbody></table><button class="secondary-button" data-action="add-parameter" style="margin-top:14px">${icon('plus')} Add parameter</button><div id="parameter-error"></div><div class="form-help">Units: millimeters and degrees. Examples: <code>160</code>, <code>baseWidth / 2</code>, <code>2 * inch</code>. Functions: sqrt, abs, min, max, sin, cos, tan, round, floor, ceil. Trigonometric arguments use degrees.</div>`,'<button class="secondary-button" data-action="close-modal">Cancel</button><button class="primary-button" data-action="save-parameters">Apply parameters</button>');updateParameterValues();}
function parameterRow(k='',v='0'){return `<tr><td><input class="param-name" value="${esc(k)}" placeholder="dimension"></td><td><input class="param-expression" value="${esc(v)}"></td><td class="param-result">—</td><td><button class="icon-button small" data-action="delete-parameter" title="Remove parameter">${icon('trash')}</button></td></tr>`;}
function readParameters(){const values=Object.create(null);for(const row of $$('#parameter-rows tr')){const k=row.querySelector('.param-name').value.trim(),value=row.querySelector('.param-expression').value.trim();if(!k)continue;if(!/^[A-Za-z_][A-Za-z_0-9]*$/.test(k)||['pi','mm','cm','m','inch','deg','__proto__','constructor','prototype'].includes(k))throw Error('Use a valid, non-reserved parameter name: '+k);if(Object.hasOwn(values,k))throw Error('Duplicate parameter: '+k);values[k]=value;}parameters(values);return values;}
function updateParameterValues(){try{const p=parameters(readParameters());for(const row of $$('#parameter-rows tr'))row.querySelector('.param-result').textContent=p[row.querySelector('.param-name').value.trim()]===undefined?'—':fmt(p[row.querySelector('.param-name').value.trim()],4);$('#parameter-error').innerHTML='';}catch(e){$('#parameter-error').innerHTML=`<div class="parameter-error">${esc(e.message)}</div>`;}}
function about(){modal('Made to make',`<div class="modal-logo"><span class="brandmark"></span><strong>alloy studio</strong><span class="release-tag">0.1 · modeling preview</span></div><p>A local-first, browser-native CAD workspace. Plain HTML, JavaScript, and a native WebGPU renderer. No framework, no CDN, no account.</p><h3>A real, deliberately bounded modeling core</h3><p>Closed sketch profiles, extrusion, revolution, parametric primitives, BSP solid Boolean operations, placement, patterns, editable feature history, mesh import/export, and surface-point measurement.</p><h3>What this build is not</h3><p>This is an independently implemented, Fusion-inspired mesh CAD application, not a drop-in replacement for Autodesk Fusion. It does not contain an analytic B-rep/NURBS kernel, arbitrary edge fillets, a general sketch constraint solver, STEP/IGES/F3D support, CAM, FEA, electronics, or assembly-joint simulation.</p><p class="small-note">Alloy Studio is not affiliated with or endorsed by Autodesk. All sample geometry is generated locally. Source code is MIT licensed.</p>`);}
function help(){const shortcuts=[['New sketch','S'],['Box','B'],['Extrude','E'],['Hole','H'],['Move / rotate','M'],['Appearance','A'],['Measure','I'],['Fit model','F'],['Projection','P'],['Grid','G'],['Search commands','⌘ / Ctrl K'],['Save project','⌘ / Ctrl S'],['Undo','⌘ / Ctrl Z'],['Redo','⌘ / Ctrl Shift Z'],['Delete selected','Delete'],['Orbit','Right drag'],['Pan','Middle drag'],['Orbit (Fusion style)','Shift + middle drag'],['Zoom to pointer','Scroll'],['Cancel / deselect','Escape']];modal('Make yourself at home',`<p>Navigate, sketch, and model without leaving the keyboard.</p><div class="shortcut-grid">${shortcuts.map(([a,b])=>`<div class="shortcut-row"><span>${a}</span><kbd>${b}</kbd></div>`).join('')}</div><h3>Sketch → solid workflow</h3><p>Press S. Drag a rectangle or circle, or select Polyline and click vertices. Finish the sketch, press E, enter a distance, and Apply. Click a feature in the timeline to change its dimensions later.</p><h3>Boolean workflow</h3><p>Create overlapping bodies. Select the target, choose Combine, then choose a tool body and Join, Cut, or Intersect. All operations remain in the editable feature history.</p><h3>Persistence</h3><p>Edits are saved in this browser’s IndexedDB. File → Save also creates a portable .alloy project. STL and OBJ export the selected body, or all visible bodies when nothing is selected.</p>`);}
function diagnostics(){const r=state.model,visible=r.bodies.filter(b=>b.visible),tris=visible.reduce((s,b)=>s+b.mesh.stats.triangles,0),bytes=r.bodies.reduce((s,b)=>s+b.mesh.positions.byteLength+b.mesh.normals.byteLength+b.mesh.indices.byteLength+b.mesh.edges.byteLength,0);modal('Engine diagnostics',`<div class="diagnostic-grid">${[[renderer.backend,'Active rendering backend'],[fmt(tris,0),'Visible triangles'],[fmt(r.elapsed,2)+' ms','Last worker regeneration'],[fmt(renderer.encodedMs,2)+' ms','Last CPU frame encode'],[fmt(bytes/1024/1024,2)+' MB','Transferred mesh buffers'],[r.features||state.doc.features.length,'Parametric features']].map(([v,k])=>`<div class="diagnostic-tile"><strong>${v}</strong><span>${k}</span></div>`).join('')}</div><h3>Architecture</h3><p>Float64 CPU geometry → worker-side dependency cache and BVH → transferable mesh arrays → batched indexed GPU geometry. Camera, hover, and selection updates write uniforms; geometry is only uploaded on model or presentation changes.</p><p>WebGPU rendering: 4× MSAA, depth buffer, a 2048² directional shadow map, GGX direct lighting, procedural studio reflections, analytic grid, and a separate edge pass. The compatibility backend is labeled explicitly.</p><p class="small-note">Timing values are measurements on this browser. CPU encode time is not GPU execution time and is not a frame-rate benchmark. No hardware performance claim is implied.</p>${renderer.lastGPUError?`<div class="parameter-error">${esc(renderer.lastGPUError)}</div>`:''}`);}
function projects(){modal('Design library',`<p>Explore a parametric assembly, build a machined part, or begin with a clean workspace.</p><div class="project-grid">${[['bearing','Orbital bearing mount','12 bodies · editable engineering assembly','design','MECHANICAL ASSEMBLY'],['flange','Precision flange','Bored hub · bolt-circle pattern','cylinder','PARAMETRIC PART'],['blank','Blank design','Your next idea starts here','plus','NEW DESIGN']].map(([id,title,sub,ic,tag])=>`<button class="project-tile" data-project="${id}"><div class="project-art"><span class="art-tag">${tag}</span>${icon(ic)}</div><div><strong>${title}</strong><small>${sub}</small></div></button>`).join('')}</div><div class="form-help">Opening a sample replaces the current design. Save a .alloy project first to retain your own changes.</div>`);}
function flangeDocument(){const d=newDocument();d.name='Precision flange';d.parameters={diameter:100,thickness:12,bore:14};let id='plate';d.features.push({id,type:'cylinder',name:'Flange',material:'aluminum',p:{radius:'diameter / 2',height:'thickness'}});d.features.push({id:'hub',type:'cylinder',name:'Hub',p:{radius:27,height:26,z:10},material:'aluminum'});d.features.push({id:'join',type:'boolean',name:'Join hub',target:id,tool:'hub',p:{operation:'union'}});id='join';for(let i=0;i<6;i++){const a=i/6*Math.PI*2;d.features.push({id:'bolt'+i,type:'hole',name:'Bolt hole '+(i+1),target:id,p:{radius:4.2,depth:14,z:-1,x:37*Math.cos(a),y:37*Math.sin(a)}});id='bolt'+i;}d.features.push({id:'bore',type:'hole',name:'Central bore',target:id,p:{radius:'bore',depth:38,z:-1}});return d;}
function loadDocument(d){state.doc=validateDocument(d);state.history=new History();state.selected=null;state.selectedFeature=null;state.form=null;state.preview=false;state.measure=null;state.sketch=null;state.dirty=true;state.ready=false;firstModel=true;renderer.selected=null;renderer.section.enabled=false;renderer.explode=0;renderer.camera.setView('iso');$('#inspector').classList.add('hidden');$('#sketch-footer').classList.add('hidden');$('#app').classList.remove('sketch-mode');closeModal();setTitle();renderRibbon();scheduleSave();rebuild();}
function searchCommands(){closeMenu();$('#modal-layer').innerHTML=`<div class="modal-scrim"><div class="modal palette" role="dialog" aria-label="Command search"><div class="palette-search">${icon('search')}<input id="palette-input" placeholder="What would you like to make?" autocomplete="off"><kbd>ESC</kbd></div><div class="palette-results" id="palette-results"></div></div></div>`;filterCommands('');$('#palette-input').focus();}
function filterCommands(query){const results=commands.filter(c=>c[1].toLowerCase().includes(query.toLowerCase())).slice(0,14);$('#palette-results').innerHTML=results.map(([id,label,ic,key])=>`<button data-command="${id}">${icon(ic)}<span>${esc(label)}</span>${key?`<kbd>${esc(key)}</kbd>`:''}</button>`).join('');}
function selectedExportBodies(){const b=selectedBody();return b?[b]:state.model.bodies.filter(b=>b.visible);}
async function importFile(file){try{if(file.size>30*1024*1024)throw Error('File exceeds the 30 MB import budget.');const ext=file.name.split('.').at(-1).toLowerCase();if(ext==='alloy'||ext==='json'){loadDocument(JSON.parse(await file.text()));toast('Project opened.');return;}const faces=ext==='stl'?importSTL(await file.arrayBuffer()):ext==='obj'?importOBJ(await file.text()):null;if(!faces)throw Error('Supported files: .alloy, .json, .stl, .obj.');if(faces.length>100000)throw Error('Imported mesh exceeds the 100,000-face budget.');const feature={id:uid(),type:'mesh',name:file.name.replace(/\.[^.]+$/,''),material:'aluminum',p:{faces:faces.map(f=>f.v)}};firstModel=true;commit('Import '+file.name,d=>d.features.push(feature));state.selected=feature.id;toast(`${fmt(faces.length,0)} mesh faces imported. Units interpreted as millimeters.`);}catch(e){toast(e.message,true);}}
async function capturePNG(){try{renderer.resize();if(renderer.backend==='WebGPU'){renderer.drawGPU();await renderer.gpu.queue.onSubmittedWorkDone();}else renderer.drawGL();const blob=await new Promise(resolve=>renderer.canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('Could not capture the viewport.');download(blob,filename('png'));toast('Viewport captured as PNG.');}catch(e){toast(e.message,true);}}
function exportDrawing(){const bodies=selectedExportBodies();if(!bodies.length){toast('Nothing to export.');return;}const paths=[],project=p=>renderer.camera.project(p);let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const b of bodies){const lines=b.mesh.edges;for(let i=0;i<lines.length;i+=6){const a=project([lines[i],lines[i+1],lines[i+2]]),c=project([lines[i+3],lines[i+4],lines[i+5]]);minX=Math.min(minX,a[0],c[0]);maxX=Math.max(maxX,a[0],c[0]);minY=Math.min(minY,a[1],c[1]);maxY=Math.max(maxY,a[1],c[1]);paths.push(`M${a[0].toFixed(3)} ${a[1].toFixed(3)}L${c[0].toFixed(3)} ${c[1].toFixed(3)}`);}}
  const w=maxX-minX+70,h=maxY-minY+120;if(!Number.isFinite(w)||!paths.length){toast('No edges available.');return;}const text=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${minX-35} ${minY-35} ${w} ${h}"><rect x="${minX-35}" y="${minY-35}" width="${w}" height="${h}" fill="white"/><path d="${paths.join('')}" stroke="#284252" stroke-width=".65" fill="none"/><text x="${minX}" y="${maxY+45}" font-family="sans-serif" font-size="16" fill="#284252">${esc(state.doc.name)}</text><text x="${minX}" y="${maxY+64}" font-family="sans-serif" font-size="9" fill="#7b8c97">ALLOY STUDIO · PROJECTED EDGES · NOT TO SCALE · HIDDEN EDGES INCLUDED</text></svg>`;download(text,filename('svg'),'image/svg+xml');toast('Projected edge drawing exported. Hidden edges are included; drawing is not to scale.');}
async function command(id,event=null){
  if($('#palette-input'))closeModal();closeMenu();
  switch(id){
    case 'box':case 'cylinder':case 'sphere':case 'torus':case 'extrude':case 'revolve':case 'hole':case 'boolean':case 'move':case 'pattern':openFeature(id);break;
    case 'create-sketch':startSketch();break;
    case 'finish-sketch':finishSketch();break;
    case 'rectangle':case 'circle':case 'polygon':if(!state.sketch)startSketch();state.sketch.tool=id;state.sketch.start=null;state.sketch.points=[];renderRibbon();showSketchPalette();break;
    case 'sketch-undo':if(state.sketch){if(state.sketch.points.length)state.sketch.points.pop();else state.sketch.profiles.pop();showSketchPalette();renderer.invalidate();}break;
    case 'sketch-clear':if(state.sketch){state.sketch.profiles=[];state.sketch.points=[];showSketchPalette();renderer.invalidate();}break;
    case 'sketch-snap':if(state.sketch){state.sketch.snap=!state.sketch.snap;showSketchPalette();}break;
    case 'show-sketches':state.showSketches=!state.showSketches;renderer.invalidate();toast(state.showSketches?'Sketch profiles visible.':'Sketch profiles hidden.');break;
    case 'parameters':showParameters();break;
    case 'appearance':if(!state.selected){toast('Select a body to assign an appearance.');break;}showSelection();$('#inspector .material-grid')?.scrollIntoView({block:'nearest'});break;
    case 'measure':state.measure={points:[]};state.nav='select';showMeasure();renderer.invalidate();break;
    case 'section':renderer.section.enabled=true;renderer.shadowDirty=true;showSection();renderer.invalidate();break;
    case 'view-options':viewOptions();break;
    case 'explode':renderer.explode=renderer.explode?0:.65;renderer.upload();viewOptions();break;
    case 'home':renderer.camera.setView('iso');renderer.camera.fit(renderer.bounds);renderer.invalidate();break;
    case 'fit':{const b=selectedBody();renderer.camera.fit(b?.mesh.stats.bounds||renderer.bounds);renderer.invalidate();break;}
    case 'grid':renderer.grid=!renderer.grid;renderer.invalidate();break;
    case 'projection':renderer.camera.ortho=!renderer.camera.ortho;renderer.invalidate();updateStats();break;
    case 'orbit':case 'pan':state.nav=state.nav===id?'select':id;$$('#navigation button').forEach(b=>b.classList.toggle('active',b.dataset.command===state.nav));status(state.nav==='select'?'Select a body · Right-drag to orbit':state.nav==='orbit'?'Orbit tool · drag the viewport to rotate':'Pan tool · drag the viewport to translate');break;
    case 'undo':case 'redo':{if(state.sketch){command('sketch-undo');break;}const entry=state.history[id](state.doc);if(entry){state.doc=entry.doc;state.preview=false;state.selectedFeature=null;state.form=null;$('#inspector').classList.add('hidden');setTitle();scheduleSave();rebuild();toast(`${id==='undo'?'Undid':'Redid'} ${entry.label}`);}break;}
    case 'delete':{const b=selectedBody();if(!b){toast('Select a body to delete.');break;}commit('Delete '+b.name,d=>d.features.push({id:uid(),type:'delete',name:'Delete '+b.name,target:b.id,p:{}}));state.selected=null;closeInspector();break;}
    case 'duplicate':{const b=selectedBody();if(b){openFeature('pattern');$('#feature-form').elements.count.value=2;}break;}
    case 'save':download(JSON.stringify(state.doc,null,2),filename('alloy'),'application/json');toast('Editable project saved.');break;
    case 'import':$('#file-input').click();break;
    case 'export-stl':{const bs=selectedExportBodies();if(!bs.length){toast('Nothing to export.');break;}download(exportSTL(bs.map(b=>b.mesh)),filename('stl'),'model/stl');toast(`${bs.length} ${bs.length===1?'body':'bodies'} exported as binary STL (mm).`);break;}
    case 'export-obj':{const bs=selectedExportBodies();if(!bs.length){toast('Nothing to export.');break;}download(exportOBJ(bs),filename('obj'),'text/plain');toast('OBJ exported in millimeters.');break;}
    case 'drawing':exportDrawing();break;
    case 'screenshot':await capturePNG();break;
    case 'new':modal('Create a new design','<p>Your current design will be replaced in the local workspace. Save an Alloy project first to keep a portable copy.</p>','<button class="secondary-button" data-action="close-modal">Cancel</button><button class="secondary-button" data-command="save">Save current design</button><button class="primary-button" data-project="blank">Create new</button>');break;
    case 'projects':projects();break;
    case 'about':about();break;
    case 'help':help();break;
    case 'diagnostics':diagnostics();break;
    case 'search':searchCommands();break;
    case 'collapse-browser':$('#browser').classList.toggle('collapsed');setTimeout(()=>renderer.invalidate(),180);break;
    case 'history-start':state.doc.rollback=state.doc.features.length?0:null;rebuild();break;
    case 'history-end':state.doc.rollback=null;rebuild();break;
    case 'history-prev':if(state.doc.features.length){state.doc.rollback=Math.max(0,(state.doc.rollback??state.doc.features.length-1)-1);rebuild();}break;
    case 'history-next':if(state.doc.rollback!==null){state.doc.rollback++;if(state.doc.rollback>=state.doc.features.length-1)state.doc.rollback=null;rebuild();}break;
    case 'rename':modal('Rename design',`<label class="field full"><span>Design name</span><input id="design-name" value="${esc(state.doc.name)}" maxlength="200"></label>`,'<button class="secondary-button" data-action="close-modal">Cancel</button><button class="primary-button" data-action="rename-design">Rename</button>');break;
    default:console.warn('Unknown command',id);
  }
}
function bindUI(){
  document.addEventListener('click',e=>{
    const cmd=e.target.closest('[data-command]');if(cmd){command(cmd.dataset.command,e);return;}
    const view=e.target.closest('[data-view]');if(view){renderer.camera.setView(view.dataset.view);renderer.camera.ortho=true;renderer.invalidate();updateStats();return;}
    const folder=e.target.closest('[data-folder]');if(folder){state.folders[folder.dataset.folder]=!state.folders[folder.dataset.folder];renderBrowser();return;}
    const visibility=e.target.closest('[data-toggle-body]');if(visibility){const id=visibility.dataset.toggleBody;commit('Toggle visibility',d=>{const at=d.hidden.indexOf(id);if(at<0)d.hidden.push(id);else d.hidden.splice(at,1);});return;}
    const body=e.target.closest('[data-body]');if(body){select(body.dataset.body);return;}
    const sketch=e.target.closest('[data-sketch]');if(sketch){select(sketch.dataset.sketch);return;}
    const feature=e.target.closest('[data-feature]');if(feature){const f=state.doc.features.find(f=>f.id===feature.dataset.feature);if(f.type==='delete'){toast('This feature removes a body. Undo it or suppress it from its timeline context menu.');return;}openFeature(f.type,f);return;}
    const tab=e.target.closest('[data-tab]');if(tab){if(state.sketch&&tab.dataset.tab!=='sketch'){toast('Finish or cancel the current sketch first.');return;}state.tab=tab.dataset.tab;renderRibbon();return;}
    const plane=e.target.closest('[data-plane]');if(plane){startSketch(plane.dataset.plane);return;}
    const material=e.target.closest('[data-material]');if(material){if(state.selected)commit('Change appearance',d=>d.appearances[state.selected]=material.dataset.material);return;}
    const project=e.target.closest('[data-project]');if(project){loadDocument(project.dataset.project==='bearing'?demoDocument():project.dataset.project==='flange'?flangeDocument():newDocument());return;}
    const style=e.target.closest('[data-style]');if(style){renderer.style=Number(style.dataset.style);renderer.invalidate();viewOptions();updateStats();return;}
    const action=e.target.closest('[data-action]');if(action){handleAction(action.dataset.action,action);return;}
    if(e.target.classList.contains('modal-scrim'))closeModal();
    if(!e.target.closest('.menu')&&!e.target.closest('#file-menu')&&!e.target.closest('#workspace-menu'))closeMenu();
    if(e.target.closest('[data-select="root"]')){select(null,false);command('rename');}
  });
  $('#file-menu').addEventListener('click',e=>{e.stopPropagation();menu(e.currentTarget,[['new','New design','file',''],['projects','Design library','library'],['import','Open / import','import'],['save','Save project','save','⌘ S'],['rename','Rename design','edit'],'-',['export-stl','Export STL','export'],['export-obj','Export OBJ','export'],['drawing','Export SVG drawing','drawing'],['screenshot','Capture PNG','camera'],'-',['about','About Alloy Studio','info']]);});
  $('#workspace-menu').addEventListener('click',e=>{e.stopPropagation();menu(e.currentTarget,[['projects','Design library','library'],['view-options','Design workspace','design'],['drawing','Export drawing','drawing'],['about','Capabilities and scope','info']]);});
  $('#browser-filter').addEventListener('input',renderBrowser);$('#file-input').addEventListener('change',e=>{if(e.target.files[0])importFile(e.target.files[0]);e.target.value='';});
  document.addEventListener('input',e=>{
    if(e.target.id==='palette-input')filterCommands(e.target.value);
    if(e.target.closest('#parameter-rows'))updateParameterValues();
    if(e.target.id==='section-slider'){renderer.section.offset=Number(e.target.value);const f=$('[name=section-offset]');if(f)f.value=e.target.value;renderer.shadowDirty=true;renderer.invalidate();}
    if(e.target.id==='explode-slider'){renderer.explode=Number(e.target.value);renderer.upload();}
  });
  document.addEventListener('change',e=>{const el=e.target,n=el.name;
    if(el.id==='rename-body'){const b=selectedBody();if(b&&el.value.trim()){const name=el.value.trim().slice(0,150);commit('Rename body',d=>{d.names??={};d.names[b.id]=name;});}}
    if(state.sketch){const s=state.sketch;if(n==='sketch-plane'){if(s.profiles.length||s.points.length){el.value=s.plane;toast('Finish the existing profiles before changing planes.');return;}s.plane=el.value;renderer.camera.setView(s.plane==='XY'?'top':s.plane==='XZ'?'front':'right');showSketchPalette();}if(el.id==='sketch-snap')s.snap=el.checked;if(n==='sketch-spacing'){s.spacing=clamp(Number(el.value)||1,.1,100);el.value=s.spacing;}if(n?.startsWith('profile-')){const p=s.profiles.at(-1);if(p)p[n.slice(8)]=clamp(Number(el.value)||1,.01,100000);}renderer.invalidate();}
    if(el.id==='section-enabled'){renderer.section.enabled=el.checked;renderer.shadowDirty=true;renderer.invalidate();}
    if(n==='section-axis'){renderer.section.axis=el.value;showSection();renderer.shadowDirty=true;renderer.invalidate();}
    if(n==='section-offset'){renderer.section.offset=Number(el.value)||0;renderer.shadowDirty=true;renderer.invalidate();}
    if(el.id==='perspective-setting'){renderer.camera.ortho=!el.checked;renderer.invalidate();updateStats();}
    if(el.id==='grid-setting'){renderer.grid=el.checked;renderer.invalidate();}
    if(el.id==='show-sketches-setting'){state.showSketches=el.checked;renderer.invalidate();}
  });
  document.addEventListener('keydown',e=>{const editing=/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName),meta=e.ctrlKey||e.metaKey,key=e.key.toLowerCase();if(key==='escape'){e.preventDefault();if($('#modal-layer').children.length){closeModal();return;}closeMenu();if(state.sketch){state.sketch.start=null;state.sketch.points=[];renderer.invalidate();return;}state.measure=null;state.nav='select';select(null);renderer.invalidate();return;}
    if($('#palette-input')){if(key==='enter'){e.preventDefault();$('#palette-results button')?.click();}return;}
    if(editing){if(key==='enter'&&e.target.closest('#feature-form')&&e.target.tagName!=='TEXTAREA'){e.preventDefault();applyFeature();}return;}
    if(meta&&['s','z','y','k','o'].includes(key)){e.preventDefault();command(key==='s'?'save':key==='k'?'search':key==='o'?'import':key==='y'||e.shiftKey?'redo':'undo');return;}
    if(state.sketch){if(key==='enter'){closePolygon();return;}if(['r','c','l'].includes(key)){command({r:'rectangle',c:'circle',l:'polygon'}[key]);return;}if(key==='backspace'||key==='delete'){e.preventDefault();command('sketch-undo');return;}}
    const map={s:'create-sketch',b:'box',e:'extrude',h:'hole',m:'move',a:'appearance',i:'measure',f:'fit',p:'projection',g:'grid','?':'help',delete:'delete',backspace:'delete'};if(map[key]){e.preventDefault();command(map[key]);}if(key==='/'){e.preventDefault();$('#browser-filter').focus();}
  });
  $('#timeline').addEventListener('contextmenu',e=>{const b=e.target.closest('[data-feature]');if(!b)return;e.preventDefault();const id=b.dataset.feature,feature=state.doc.features.find(f=>f.id===id),index=state.doc.features.indexOf(feature);closeMenu();const el=document.createElement('div');el.className='menu';el.style.left=Math.min(e.clientX,innerWidth-250)+'px';el.style.top=Math.max(10,e.clientY-137)+'px';el.innerHTML=`<div class="menu-title">${esc(feature.name)}</div><button data-action="context-edit" data-id="${esc(id)}">${icon('edit')}Edit feature</button><button data-action="context-suppress" data-id="${esc(id)}">${icon('eye-off')}${feature.suppressed?'Unsuppress':'Suppress'} feature</button><button data-action="context-rollback" data-index="${index}">${icon('back')}Roll history to here</button>`;$('#menu-layer').append(el);});
  $('#stage').addEventListener('dragover',e=>{e.preventDefault();});$('#stage').addEventListener('drop',e=>{e.preventDefault();if(e.dataTransfer.files[0])importFile(e.dataTransfer.files[0]);});
}
function handleAction(action,el){
  switch(action){
    case 'close-modal':closeModal();break;
    case 'close-inspector':if(state.sketch){cancelSketch();break;}state.measure=null;closeInspector();renderer.invalidate();break;
    case 'apply-feature':applyFeature(false);break;
    case 'preview-feature':applyFeature(true);break;
    case 'edit-source':{const b=selectedBody(),f=state.doc.features.find(f=>f.id===b?.featureId);if(f)openFeature(f.type,f);break;}
    case 'cancel-sketch':cancelSketch();break;
    case 'reset-measure':state.measure={points:[]};showMeasure();renderer.invalidate();break;
    case 'finish-measure':state.measure=null;closeInspector();renderer.invalidate();break;
    case 'add-parameter':$('#parameter-rows').insertAdjacentHTML('beforeend',parameterRow());$('#parameter-rows tr:last-child .param-name').focus();break;
    case 'delete-parameter':el.closest('tr').remove();updateParameterValues();break;
    case 'save-parameters':try{const p=readParameters();commit('Change parameters',d=>d.parameters=p);closeModal();toast('User parameters updated.');}catch(e){$('#parameter-error').innerHTML=`<div class="parameter-error">${esc(e.message)}</div>`;}break;
    case 'rename-design':{const name=$('#design-name').value.trim();if(name){commit('Rename design',d=>d.name=name);closeModal();}break;}
    case 'context-edit':{const f=state.doc.features.find(f=>f.id===el.dataset.id);closeMenu();if(f&&f.type!=='delete')openFeature(f.type,f);break;}
    case 'context-suppress':{const id=el.dataset.id;closeMenu();commit('Toggle feature suppression',d=>{const f=d.features.find(f=>f.id===id);f.suppressed=!f.suppressed;});break;}
    case 'context-rollback':state.doc.rollback=Number(el.dataset.index);closeMenu();rebuild();break;
  }
}
async function main(){
  hydrateIcons();renderRibbon();renderBrowser();renderTimeline();bindUI();
  if(innerWidth<760)$('#browser').classList.add('collapsed');
  renderer=new Renderer($('#viewport'));renderer.onError=message=>{console.warn(message);if(renderer.backend==='WebGPU'||renderer.backend==='Device lost')toast(message,true);};
  try{await renderer.initialize();renderer.onFrame=()=>{drawOverlay();updateStats();};bindViewport();await initStorage();createWorker();setTitle();rebuild();}catch(e){$('#loading').innerHTML=`<span>Renderer initialization failed</span><small>${esc(e.message)}</small><button class="primary-button" data-command="help">Help</button>`;console.error(e);}
}
// Public, intentionally small automation/debug surface; no executable document strings.
globalThis.Alloy={get ready(){return state.ready;},get document(){return clone(state.doc);},get model(){return state.model;},get renderer(){return renderer;},get state(){return state;},command,loadDocument,createDemo:demoDocument,createFlange:flangeDocument,rebuild,select,tests:{expression,parameters},version:'0.1.0'};
main();
